name: CI-CD Docker Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for pnpm if needed)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/aiwebchat-web:latest

      - name: Build & Push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/aiwebchat-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and deploy with docker-compose
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            # 部署目录（自定义）
            APP_DIR=/opt/aiwebchat
            mkdir -p $APP_DIR
            cd $APP_DIR

            # 如果第一次部署，创建 docker-compose.yml 和 .env
            if [ ! -f docker-compose.yml ]; then
              cat > docker-compose.yml <<'COMPOSE'
            version: "3.9"
            services:
              api:
                image: ghcr.io/${{ secrets.GHCR_USERNAME }}/aiwebchat-api:latest
                container_name: aiwebchat-api
                restart: unless-stopped
                environment:
                  - NODE_ENV=production
                  - PORT=8787
                  - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
                  - DEEPSEEK_BALANCE_URL=${DEEPSEEK_BALANCE_URL}
                networks:
                  - appnet

              web:
                image: ghcr.io/${{ secrets.GHCR_USERNAME }}/aiwebchat-web:latest
                container_name: aiwebchat-web
                restart: unless-stopped
                depends_on:
                  - api
                ports:
                  - "10004:80"
                networks:
                  - appnet

            networks:
              appnet:
                driver: bridge
            COMPOSE
            fi

            if [ ! -f .env ]; then
              cat > .env <<'ENVVARS'
            DEEPSEEK_API_KEY=sk-REPLACE_ME
            # 可选：如果已确定余额接口
            # DEEPSEEK_BALANCE_URL=https://api.deepseek.com/v1/user/balance
            ENVVARS
              echo "请在服务器 $APP_DIR/.env 中替换 DEEPSEEK_API_KEY"
            fi

            # 拉取最新镜像并重启
            docker compose pull
            docker compose up -d
            docker image prune -f
